name: CICD

on:
  push:
    branches:
      - "main"

jobs:
  preparation:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, this is test pipeline"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd cicd-demo
            git pull origin main
            docker compose build --no-cache
            docker compose down
            docker compose up -d
            
    needs: [preparation] 
